"Platform-neutral capability interfaces with explicit unsupported results."
from __future__ import annotations
from dataclasses import dataclass
from pathlib import Path
from typing import Protocol
@dataclass
class CapabilityResult:
    success: bool
    message: str
    data: dict | None = None
    @classmethod
    def unsupported(cls, capability: str) -> "CapabilityResult":
        return cls(False, f"{capability} is not supported by this platform client.", {})

class ApplicationManager(Protocol):
    def discover(self, query: str) -> list[str]: ...
    def open(self, name: str) -> CapabilityResult: ...

class BrowserManager(Protocol):
    def navigate(self, url: str) -> CapabilityResult: ...
    def observe(self) -> CapabilityResult: ...

class CodingAgent(Protocol):
    def detect(self) -> CapabilityResult: ...
    def open_project(self, project: Path) -> CapabilityResult: ...
    def insert_prompt(self, prompt: str) -> CapabilityResult: ...
    def submit_prompt(self) -> CapabilityResult: ...
    def wait_for_completion(self) -> CapabilityResult: ...

class MobileManager(Protocol):
    "Client-provided mobile capabilities; server never pretends to own them."
    def open_app(self, package_or_url: str) -> CapabilityResult: ...
    def install(self, package_or_url: str) -> CapabilityResult: ...
